# Encéfalo

Do ponto de vista neuroanatômico, o encéfalo corresponde à parte superior e de maior organização citoarquitetural do Sistema Nervoso Central (ou neuroeixo), estando constituído pela união de telencéfalo, diencéfalo, mesencéfalo, ponte, bulbo e cerebelo e delimitado inferiormente pela decussação das pirâmides bulbares, ponto da via corticoespinal fundamental para a projeção de eferências motoras. Funcionalmente, as estruturas encefálicas medeiam uma série de processos fisiológicos responsáveis por integrar as funções vegetativas do organismo e perceber e interpretar aspectos variados da interface entre este e o meio no qual ele se encontra inserido, a exemplo das funções cronobiológicas do núcleo supraquiasmático e da glândula epífise, do controle da fome e da ingestão alimentar determinado pela atividade de núcleos hipotalâmicos, da interpretação da linguagem promovida pela área de Wernicke e da decodificação visual efetuada por áreas secundárias do lobo occipital. Cabe também ressaltar que o encéfalo é responsável pelo controle de funções executivas superiores e pela realização do pensamento crítico complexo por intermédio de intrincados circuitos neuronais ainda não muito bem compreendidos, os quais possuem altas potências de plasticidade e se relacionam à personalidade, à motivação, à memória, ao comportamento e a outros fenômenos misteriosos da Neurofisiologia.

Nesse sentido, é válido destacar que a consciência - tida como provavelmente a maior incógnita das neurociências - também advém das complexas organizações celulares e bioquímicas dos componentes do encéfalo, com especial destaque para o córtex cerebral. Desde a Antiguidade, múltiplas hipóteses têm sido formuladas a fim de se desvelar os mecanismos biofísicos e filosóficos subjacentes a tal fenômeno central da experiência humana, sendo que a Teoria da Complexidade configura-se atualmente como a proposta mais aceita pela comunidade científica para a explicação da consciência e de suas origens. Esta se originou no campo da Matemática e da Engenharia da Computação e postula que existe uma tendência natural de ocorrerem fenômenos dinâmicos não triviais em extensas redes de elementos interconectados, o que oferece uma base para a explicação de como a consciência poderia emergir a partir de uma circuitaria altamente complexa e organizada de células excitáveis. Nesse âmbito, pode-se citar que empreitadas científicas como o Projeto Conectoma Humano, que visa ao mapeamento de todo o conjunto de sinapses existentes no Sistema Nervoso, são fundamentais não só para o aprimoramento da prática clínica como também para uma melhor compreensão da Biologia Celular e da Bioquímica que regem a Histofisiologia de um dos sistemas mais enigmáticos do organismo humano.

## Tecido Nervoso

Conforme proposto pelo neuroanatomista espanhol Santiago Ramón y Cajal, o tipo celular característico do Sistema Nervoso consiste numa célula altamente especializada estacionada mitoticamente na fase G~0~ e condutora de impulsos elétricos, por meio dos quais pode induzir a excitação de outras células: o neurônio.

Entretanto, deve-se ressaltar que, para que este cumpra corretamente seus papéis fisiológicos, faz-se necessária a presença de células de sustentação responsáveis por nutrirem, protegerem e mielinizarem os neurônios: as células da glia. Há estudos que apontam que essas células de características estromais são cerca de três vezes mais numerosas que os próprios neurônios e que, assim como eles, também apresentam padrões morfológicos extremamente específicos, que abrangem desde células com prolongamentos bastante ramificados a células de caráter epitelial cúbico simples com microvilosidades em suas membranas apicais.

No que tange à histogênese das populações celulares do tecido nervoso, é importante salientar que tanto os neurônios quanto as células da glia possuem origem embrionária neuroectodérmica, diferenciando-se a partir de precursores presentes nas zonas ventricular, intermediária e cortical do tubo neural por meio da ação de morfógenos como o fator de transcrição $SOX9$, o fator nuclear $I/A$, a glicoproteína $Wnt$ e a proteína sinalizadora $SHH$ (*sonic hedgehog*). Cabe mencionar, todavia, que as células da micróglia constituem uma importante exceção a esse padrão, originando-se de células mesenquimais precursoras eritromieloides encontradas no saco vitelínico. As células da micróglia apresentam em suas superfícies receptores para quimiocinas e outras moléculas inflamatórias, o que demonstra que elas possuem importantes funções no desenrolar da resposta imune inata e adaptativa no tecido nervoso. Nesse quesito, cabe dizer que a micróglia constitui parte do chamado Sistema Fagocítico Mononuclear, assim como as células de Kupffer, os osteoclastos e os macrófagos, compartilhando parte significativa de seu proteoma com essas células, a exemplo da proteína transmembrânica 19 $(TMEM19)$, do purinorreceptor P2Y $(P2RY12)$ e da proteína Sal-símile 1 $(SALL1)$

### Neurônios {.unnumbered}

Na microscopia de luz, o componente mais reconhecível da morfologia neuronal básica é compreendido por uma região dilatada denominada soma, pericário ou corpo celular, na qual é possível observar um núcleo claro com predomínio de eucromatina e nucléolos evidentes situado adjacente a uma área intensamente basofílica conhecida como ergastoplasma ou corpúsculo de Nissl, nome que se dá para o retículo endoplasmático rugoso nessa população celular. Essas características ultraestrutruais indicam que essas células apresentam intensa atividade de síntese proteica, o que faz sentido de um ponto de vista fisiológico, haja vista que a comunicação entre dois neurônios se dá predominantemente através da liberação de mediadores químicos em regiões do meio extracelular conhecidas como fendas sinápticas. Do ponto de vista bioquímico, essas moléculas sinalizadoras muitas vezes são aminoácidos, a exemplo da glicina e do glutamato, ou derivados de aminoácidos, como a acetilcolina e a dopamina, o que justificaria a síntese de componentes proteicos aumentada nos neurônios. Ademais, vale relembrar que, tal como os cardiomiócitos e outras células mitoticamente inativas, os neurônios apresentam grânulos de lipofuscina em seus citoplasmas, identificáveis por meio de técnicas imunohistoquímicas.

No processo de condução do impulso nervoso, corpo celular recebe potenciais excitatórios e inibitórios provenientes de pequenos prolongamentos similares aos galhos de uma árvore, denominadas dendritos (do grego; *"dendron"*, *galhos*), nos quais é possível encontrar especializações de membrana conhecidas como espículas dendríticas, que possuem a função de aumentar a superfície de contato nas sinapses axoespinhosas. Após o pericário efetuar somações espaciais e temporais dos estímulos recebidos por meio dos prolongamentos dendríticos, estes são transmitidos para um grande prolongamento cilíndrico único denominado axônio, o qual se prende ao corpo celular por meio de uma região livre de ergastoplasma denominada cone de implantação. A abertura de canais de Na^+^ voltagem-dependentes nessa região possibilita a ocorrência de um evento elétrico no qual se observa uma onda de despolarização viajando unidirecionalmente ao longo do protoplasma axonal em direção ao terminal sináptico, fenômeno conhecido como potencial de ação. Quando esse potencial de ação chega no terminal sináptico, ele promove a abertura de canais de Ca^2+^ voltagem-dependentes na membrana dessa região, permitindo a entrada de íons Ca^2+^ para o citoplasma neuronal, promovendo, por conseguinte, a exocitose de vesículas de secreção contendo neurotransmissores, os quais são liberados para a fenda sináptica.

É interessante notar que as morfologias celulares dos neurônios podem variar drasticamente de acordo com o órgão analisado e suas respectivas funções, de forma que podem ser elencados como tipos básicos de neurônios os unipolares, os bipolares, os pseudounipolares e os multiploares. Em suma, as características básicas de cada um desses perfis estruturais básicos encontram-se resumidas a seguir.

#### Neurônios unipolares {.unnumbered}

Apresentam um corpo celular do qual parte um único axônio, não possuindo prolongamentos dendríticos. São extremamente raros no organismo humano, podendo ser encontrados no epitélio sensitivo da mucosa olfatória e na retina.

#### Neurônios bipolares {.unnumbered}

Nessas células, o pericário se encontra diretamente interposto entre dois prolongamentos protoplasmáticos, sendo que o sinal recebido pelos dendritos é conduzido até o corpo celular por meio de um prolongamento citoplasmático único formado pela união dos vários dendritos. Ao chegar no corpo celular, o sinal elétrico é então transmitido até o terminal sináptico por meio do axônio. Vale frisar que é possível encontrar neurônios dessa categoria nos gânglios coclear e vestibular, na retina e na mucosa olfatória, estruturas anatômicas envolvidas na captação dos sentidos especiais.

#### Neurônios pseudounipolares {.unnumbered}

Originam-se a princípio como neurônios bipolares, porém, o corpo celular se desloca lateralmente aos prolongamentos celulares, de forma que estes se fundem num filamento contínuo em relação ao qual o corpo celular se encontra interposto indiretamente, através de uma curta ponte de citoplasma. Esses neurônios se encontram intrinsicamente relacionados à percepção sensitiva, podendo ser encontrados, por exemplo, nos gânglios sensitivos de nervos espinais e em alguns gãnglios de nervos cranianos como o trigêmeo (NC V), principal estrutura nervosa relacionada à propriocepção consciente, à sensibilidade vibratória e ao tato epicrítico na face. Dessa forma, ainda é possível pensar essa classe de neurônios como células detentoras de um prolongamento único, o qual se bifurca num prolongamento centrífugo de características dendríticas responsável por captar estímulos da periferia do organismo e num prolongamento centrípeto de natureza axonal dedicado a encaminhar tais estímulos ao Sistema Nervoso Central.

#### Neurônios multipolares {.unnumbered}

Apresentam uma morfologia celular típica do que se costuma vir à mente ao se pensar em nerurônios, com o pericário recebendo vários prolongamentos dendríticos e emitindo um único e longo prolongamento axonal. Vale mencionar que, assim como os demais tipos de neurônios previamente abordados, nos neurônios multipolares também é possível observar a presença de neurofilamentos ao longo do axônio, filamentos intermediários do tipo IV que servem como biomarcadores de diversas doenças neurodegenerativas com prognóstico grave, a exemplo da neuropatia axonal gigante, da esclerose lateral amiotrófica e da Doença de Alzheimer. Essa classe de neurônios é a mais numerosa do corpo, sendo possível encontrar uma grande pluralidade morfológica dentre os neurônios que a compõem. Tal pluralidade fica muito evidente ao compararmos neurônios multipolares de diferentes regiões do Sistema Nervoso. Enquanto as células de Betz situadas na camada piramidal interna do córtex motor primário são caracterizadas por seus formatos triangulares, as células de Purkinje do córtex cerebelar são marcadas por possuírem profusas ramificações dendríticas. Por outro lado, os neurônios parvocelulares dos núcleos hipotalâmicos responsáveis pela secreção de hormônios hipofisiotróficos são facilmente noticiáveis por conta das dimensões reduzidas do corpo celular. É importante destacar que, levando-se em consideração a extensão dos axônios dos neurônios multipolares, eles podem ainda ser separados em dois subtipos:

-   **Golgi tipo I:** apresentam axônios longos que se estendem para além dos limites da árvore dendrítica.
-   **Golgi tipo II:** seus axônios são muito curtos e não extrapolam os limites da região ocupada pelos prolongamentos dendríticos. Podem ainda ser isentas de axônios.

### Células da Glia {.unnumbered}

No que concerne às células da glia (também conhecidas como gliócitos) e suas amplas variedades histofuncionais, é possível notar que essas populações celulares possuem as capacidades necessárias para promover mecanismos de suporte às atividades de condução nervosa desempenhadas pelos neurônios, direta ou indiretamente. Nesse contexto, a fagocitose de potenciais patógenos, a produção de líquido cerebroespinal (importante fluido corporal que banha o Sistema Nervoso Central e o protege de choques mecânicos) e a realização da drenagem glinfática durante o sono podem ser elencadas como algumas das múltiplas funções desempenhadas pelos gliócitos a fim de se resguardar a homeostase do tecido nervoso. Apesar das células da glia apresentarem características morfológicas altamente diversificadas, todas elas possuem uma origem embrionária neuroectodérmica em comum, à exceção das células de micróglia.

Sob uma perspectiva patológica, é relevante destacar que, enquanto os neurônios apresentam baixas capacidades regenerativas e se encontram permanentemente estacionados na fase G~0~ do ciclo celular fora das esparsas regiões correspondentes a nichos neuronais (como o córtex entorrinal da formação hipocampal), as células da glia são mitoticamente ativas e podem se proliferar descontroladamente mediante processos neoplásicos, originando tumores conhecidos como gliomas, que, por sua vez, abrangem glioblastomas, astrocitomas, oligodendromas, Schwannomas, ependimomas, dentre outras espécies de neoplasias. Ademais, frente a processos de morte celular dos neurônios (o que pode se dar de forma mais pronunciada na Síndrome de Wernicke-Korsakoff e na Doença de Tay-Sachs), as células da glia passam a ocupar o lugar das células nervosas lesionadas, limpando restos celulares e preenchendo o tecido danificado nesse processo, de maneira análoga ao que é observado na fibrose do miocárdio após episódios isquêmicos desencadeados por obstruções das artérias coronárias. A esse processo, dá-se o nome de gliose.

Para a devida compreensão acerca das populações celulares que compõem as células de glia e suas respectivas características funcionais, é necessário termos em mente alguns pontos-chave, dos quais trataremos logo a seguir.

#### Astrócitos {.unnumbered}
