# Plexo Coroide

Sob uma óptica histológica, pode-se asserir que a população celular mais representativa das regiões nas quais se faz presente o plexo coroide corresponde às **células ependimárias**, embriologicamente derivadas das células ventriculares que povoam a zona ventricular do tubo neural durante o processo de histogênese do tecido nervoso. Além de tais células, também é possível encontrar **tanicitos** em algumas regiões específicas do sistema ventricular encefálico, os quais correspondem a células derivadas da glia radial bipolar detentoras de uma morfologia intermediária entre os astrócitos e as células ependimárias. Dessa forma, é válido frisar que as células ependimárias e os tanicitos constituem os principais componentes neuroepiteliais do epêndima, imprescindível para a produção e a movimentação do líquido cefalorraquidiano.

- boxe de Biologia Celular mostrando imagens de imunofluorescência das células ependimárias e dos tanicitos e explicando as diferenças de morfologia, com enfoque para a morfologia estranha dos tanicitos.

- boxe anatômico mostrando os componentes do sistema ventricular do Sistema Nervoso, ou seja, desde as cisternas até os ventrículos em si e os aquedutos que os conectam.

- esquema de histogênese do tecido nervoso explicado por zonas do tubo neural (pode ser aquela do Kierszenbaum)

Como já se pode inferir a partir das populações celulares gliocíticas descritas acima, o plexo coroide (ou corioide) corresponde a uma associação de **estruturas circumventriculares** e um **epêndima** de características epitelioides que abriga células especializadas na produção do líquor a partir do plasma sanguíneo. Nesse sentido, é pertinente lembrar que os chamados _órgãos circumventriculares_ são regiões do Sistema Nervoso Central nas quais se observam descontinuidades da barreira hematoencefálica e, dessa forma, representam áreas de fluxo de substâncias facilitado entre o meio intravascular e o tecido nervoso. Do ponto de vista ultraestrutural, o plexo coroide constitui-se essencialmente pela interface entre uma rede de capilares fenestrados com diafragma situada no interior de uma massa de tecido conjuntivo frouxo e o epêndima sobrejacente.

- mostrar fotomicrografia lâmina de plexo coroide indicando os componentes histológicos de suas estruturas.

Assim, pode-se dizer que o plexo coroide está presente nas paredes do terceiro e do quarto ventrículos, onde uma película fina de **pia-máter** altamente vascularizada denominada **tela coroide** oferece o aporte sanguíneo necessário para a produção de líquor e, nas fissuras coroides dos ventrículos laterais, situadas nas seções mediais desses componentes do sistema ventricular encefálico, entre o fórnice e o tálamo. Nessas regiões verifica-se, além da intensa produção de líquor, um incisivo e perene **monitoramento imunológico** por parte de macrófagos, linfócitos e células dendríticas encontradas no tecido conjuntivo frouxo que sustenta o plexo coroide.

- boxe fisiológico versando sobre a importância das células do Sistema Imunológico inclusas no plexo coroide.

Ultraestruturalmente, as células ependimárias apresentam grandes quantidades de **mitocôndrias** e múltiplas **invaginações basais** de seus domínios de membrana basolaterais, fatores que as caracterizam como células detentoras de intensa atividade metabólica e elevadas taxas de transporte ativo ocorrendo por bombas proteicas incrustadas na membrana plasmática. Ademais, a presneça de **microvilosidades** e eventuais **cílios** em seus domínios de membrana apicais é significativa do ponto de vista histofisiológico, haja vista que as células em questão também efetuam a absorção e a circulação do líquor. Finalmente, é interessante apontar a existência de uma resistente **barreira hematoliquórica** constituída por junções de oclusão e interdigitações estabelecidas entre células ependimárias adjacentes. Tais especializações laterias de membrana são, pois, fundamentais para se evitar a passagem direta de moléculas do sangue para o líquido cefalorraquidiano.

- boxe ultraestrutural mostrando eletromicrografia de transmissão do epênima, evidenciando os capilares fenestrados com diafragma que circulam pelo estroma e a Biologia Estrutural das barreiras hematoencefálica (fazer comparativo com outro corte, porque ela não vai estar presente aqui) e hematoliquórica.
