# Cerebelo

De uma perspectiva neuroanatômica, o cerebelo (cuja etimologia latina significa _pequeno cérebro_) corresponde a um órgão do compartimento infratentorial especializado em mecanismos de **coordenação motora**, **aprendizado motor** e **correção dos movimentos corporais**, conectando-se com estruturas tais como o tálamo, o complexo olivar inferior bulbar, o córtex motor, o aparellho vestibular e a medula espinal. Morfologicamente, o cerebelo se situa posteriormente ao quarto ventrículo e se conecta com o tronco encefálico por meio de três pares de pedúnculos cerebelares (superior, médio e inferior), por onde trafegam vias e tratos neuronais responsáveis pelas mais variadas funções desse componente do Sistema Nervoso, que vão desde o planejamento motor junto às áreas 5 e 7 de Brodmann até papéis límicos relacionados à linguagem e à emoção.

Assim como o cérebro, o cerebelo tabmém apresenta uma camada cortical compreendida por substância cinzenta e uma camada medular composta primordialmente por substância branca, as quais correspondem, respectivamente, ao **córtex cerebelar** e ao **corpo medular do cerebelo** (denominado também _árvore da vida_ por apresentar uma geometria similar àquela observada nos galhos de uma árvore frondosa). Podem ser encontradas esturturas compostas por substância cinzenta mergulhadas no corpo medular, coletivamente referidas como **núcleos profundos do cerebelo**. Estes abrangem os núcleos **denteado**, **interpósito** (formado pela união dos núcleos **globoso** e **emboliforme**) e **fastigial**. Do ponto de vista da divisão longitudinal do cerebelo, cada núcleo se encontra relacionado a funções e vias específicas da motricidade, o que é de grande relevância clínica para a avaliação de quadros de lesões cerebelares no exame físico.

- boxe mostrando técnicas de avaliação das vias cerebelares no exame físico neurológico

Nesse âmbito, convém salientar que a **zona verminiana**, composta por uma estrutura altamente segmentada situada ao longo do plano sagital mediano e detentora de um formato parecido com o de uma minhoca (o que justifica seu nome). Essa região se relaciona primariamente com o **núcleo do fastígio**, estabelecendo conexões com o sistema vestibular por meio da via fastígio-vestibular, essencial para o ajuste de movimentos mediante alterações nas velocidades lineares e angulares do corpo.

Por outro lado, a **zona paraverminiana**, compreendida por boa parte dos hemisérios cerebelares, relaciona-se ao **núcleo denteado** e medeia processos vinculados à intercomunicação cérebro-cerebelo para o planejamento motor por intermédio da via eferente dento-tálamo-cortical e da via aferente córtico-ponto-cerebelar. 

É necessário apontar que, assim como se pôde perceber para a classificação das regiões do córtex cerebral, o cerebelo também possui uma divisão filogenética, a qual guarda fortes correlações com os aspectos fisiológicos de cada uma de suas regiões. Destarte, é possível subdividir essa estrutura nervosa em:

-   **arquicerebelo**: funcionalmente correlacionado com o vestibulocerebelo e constituído anatomicamente pelo lobo flóculo-nodular.
-   **paleocerebelo**: fisiologicamente relacionado ao espinocerebelo.
-   **neocerebelo**: vinculado ao cerebrocerebelo do ponto de vista funcional.

No que diz respeito à anatomia microscópica desse órgão, pode-se afirmar que seu plano estratimérico básico se caracteriza pela presença de uma camada cortical externa de substância cinzenta e uma camada medular interna de substância branca, sendo que o córtex cerebelar pode ser subdividido em três estratos, os quais correspondem, de mais exterior para mais interior, a uma **camada molecular**, uma camada de **células de Purkinje** e uma camada de **células granulosas**.

De modo análogo ao que é observado para a camada molecular do córtex cerebral, a camada molecular cerebelar é relativamente pobre em corpos celulares, porém **rica em prolongamentos neuronais**. Estes incluem os prolongamentos dendríticos extremamente ramificados das células de Purkinje e os prolongamentos axônicos das células granulosas, os quais se encontram sinapticamente acoplados. Dessa forma, a ativação das células granulares por meio de **fibras musgosas** provenientes de estruturas extracerebelares promove, consequentemente, a ativação das células de Purkinje. Essa circuitaria neuronal altamente regulada constitui um dos principais aspectos da citoarquitetura cerebelar que possibilitam o aprendizado motor por meio de ativações e silenciamentos sucessivos dos neurônios situados nos núcleos profundos do cerebelo, responsáveis por dispararem as vias eferentes previamente descritas. Dentre as raras populações celulares que possuem seus pericários situados na camada molecular do córtex cerebelar, pode-se elencar as **células estreladas** e as **células em cesta**. Estas últimas podem ser classificadas como neurônios multipolares do tipo II de Golgi, configurando-se como células inibitórias $GABA$érgicas que promovem a coordenaçãomotora ao inibirem as células de Purkinje e, consequentemente, suprimirem a inibição destas sobre os núcleos cerebelares profundos.

Já a camada de **células de Purkinje** é composta primariamente por neurônios multipolares do tipo I de Golgi com grandes corpos celulares e uma profusa ramificação dendrítica direcionada para a camada molecular. Essas células são umas das maiores de todo o organismo humano e exercem ação inibitória sobre os neurônios dos núcleos profundos do cerebelo por meio da liberação de $GABA$ na fenda sináptica compreendida entre essas células ativadoras das vias cerebelares eferentes e os terminais axonais das células de Purkinje. Dessa forma, ocorre um influxo de íons Cl^-^ para o meio intracelular dos neurônios de tais núcleos, hiperpolarizando-os. As células de Pukinje são ativadas principalmente por meio da ação das **fibras trepadeiras**, que se originam do **núcleo olivar inferior** e emitem prolongamentos axônicos que parecem se entrelaçar helicoidalmente ao redor das fibras nervosas representadas pelos axônios das células de Purkinje, de modo similar ao que é constatado para as plantas epífitas, que parecem se enrolar ao redor dos troncos das árvores com as quais estabelecem relações ecológicas desarmônicas.

Por fim, cabe salientar que a **camada granulosa** do córtex cerebelar é composta primordialmente por **células granulosas**, neurônios multipolares do tipo Golgi I que emitem extensos prolongamentos axônicos retilíneos e amielínicos para a camada molecular do córtex cerebelar, e **células de Golgi**, as quais correspondem a interneurônios inibitórios $GABA$érgicos ativados pelas fibras musgosas e responsáveis por suprimirem as atividades das células granulosas. Teoriza-se que o papel das células de Golgi no contexto das intrincada circuitaria neural cerebelar esteja voltado à **plasticidade neuronal** no córtex cerebelar e ao rearranjo espaço-temporal dos níveis de atividade das células granulosas e de suas conexões sinápticas.

- boxe de biologia celular explicando os mecanismos moleculares subjacentes à plasticidade neuronal.

- boxe fisiológico explicando os papéis desempenhados pelas fibras musgosas e a neuroanatomia delas.

