# Gânglios

## Gânglios Sensitivos

As fibras sensitivas constituintes dos nervos espinais apresentam seus somas situados em dilatações localizadas na **raiz dorsal** de seus nervos, em estruturas conhecidas como **gânglios sensitivos das raízes dorsais**. Esses neurônios pseudounipolares transmitem informações sensitivas ao Sistema Nervoso Central por meio das vias **coluna dorsal-lemnisco medial**, responsável pela condução de informações relacionadas ao tato epicrítico, à sensibilidade vibratória e à propriocepção consciente de todo o corpo com exceção da cabeça e do pescoço, e **anterolateral**, a qual conduz informações relacionadas ao tato protopático, à propriocepção inconsciente, à nocicepção e à termocepção. 

<!-- - Boxe fisiológico e farmacológico sobre os anestésicos locais e a fisiologia das células nociceptivas. -->

<!-- - Boxe histórico sobre a Lei de Hilton e a Lei da Energia Específica dos Nervos. -->

Como característica histológica peculiar dos gânglios sensitivos, é possível mencionar a presença de gliócitos especializados, denominados **células satélites**, "contornando" e sustentando os corpos celulares e os neuritos dos neurônios sensitivos. Ao emitirem um prolongamento centrípeto em direção à medula espinal e um prolongamento centrífugo em direção à periferia do organismo, os gânglios sensitivos proporcionam a integração somatossensorial entre diferentes regiões do corpo, o que é de especial importância para a defesa do organismo e para a mediação de **arcos reflexos**.

<!-- - boxe fisiológico sobre a Fisiologia dos arcos reflexos e as manobras de testagem de reflexos mais relevantes no exame físico neurológico. -->

## Gânglios Autonômicos

Essas estruturas integram a **divisão visceral** do Sistema Nervoso e são fundamentais para o controle das funções vegetaticas, estabelecendo conexões com os gânglios pré-vertebrais simpáticos, os gânglios das cadeias paravertebrais e  os núcleos intermédio-mediais da medula espinal. Nesse sentido, vale salientar que, nas lâminas observadas, verifica-se a presença dessas estruturas no **Sistema Nervoso Entérico**, onde formam o **plexo mioentérico** (ou de **Auerbach**), situado entre as camadas musculares circular interna e longitudinal externa do intestino e envolvido na regulação da motilidade destas, e o **plexo submucoso** (ou de **Meissner**), localizado na camada submucosa e essencial para o controle da motilidade do estrato muscular da mucosa e para o controle quimioceptivo e mecanoceptivo da peristalse.

<!-- - Boxe de biologia celular versando sobre a importância do SNE na patogenia de doenças psíquicas e sobre as principais funções dele. -->

Ainda se pode vislumbrar a presneça de pequenos gânglios autonômicos em meio ao tecido conjuntivo presente nas trabéculas da **glãndula submandibular**, onde medeia suas atividades secretórias conectando-se com fibras provenientes do nervo facial.

## Aplicação Clínica

O vírus causador da _Herpes zoster_ tende a se alojar nos gânglios sensitivos das raízes dorsais dos nervos espinais quando se converte em seu estado latente após uma primoinfecção. Assim, mediante episódios de imunossupressão intensa, esse patógeno pode voltar à sua forma ativa e proporcionar o aparecimento de feridas máculo-papulares e vesiculares que se distribuem metamericamente na superfície do corpo, obedecendo os padrões de delimitação dos **dermátomos**. Cabe ressaltar que essas lesões podem ser desencadeadas por estresse emocional severo e podem ulcerar se deixadas sem tratamento, o que favorece a ocorrência de infecções secundárias.

<!-- - Boxe anatômico e embriológico sobre os dermátomos e os gradientes morfogenéticos que estão por trás de sua origem no desenvolvimento. -->