# Drogas de Abuso

Do ponto de vista do Código Penal Brasileiro, as drogas de abuso podem ser classificadas em lícitas (a exemplo do álcool e da nicotina, substâncias que apresentam alto potencial dependogênico em função da comercialização disseminada e da maior aceitação social para com sua utilização, que pregressamente era vista até mesmo como distintivo de _status_ econômico) e ilícitas (grupo que inclui a maconha, o ácido lisérgico, as anfetaminas, o MDMA, o _skank_, os inalantes, as _club drugs_ e inúmeras outras substâncias que constituem problemas de saúde pública de proporções geopolíticas ao se considerar o impasse do tráfico internacional de drogas e o surgimento de extensas cenas de uso intinerantes que moldam o cenário das grandes metrópoles, como a _Cracolândia_ paulistana e a _Skid Row_ em Los Angeles). Vla salientar que inúmeras substâncias originalmente planejadas como fármacos passaram a apresentar um caráter de droga de abuso como consequência de fenômenos relacionados à medicalização da vida moderna e à automedicação, haja vista a incidência crescente de síndromes de abstinência ocasionadas pela retirada de benzodiazepínicos e drogas-Z em indivíduos que realizavam uso cotidiano desses medicamentos para dormir. Nesse sentido, tem-se observado que, seguindo as recomendações de agências reguladoras como a _CDC_, muitos entes federados estadunidenses vêm aplicando restrições cada vez mais duras sobre a distruibuição e a fabricação de opioides potentes como o fentanil, o qual, embora possa apresentar um emprego muito valioso na forma de adesivos transdérmicos para o manejo da dor em pacientes em Cuidados Paliativos, tem contribuído para a epidemia de abuso de opioides que assola o país desde o final da década de 90. Sob o ponto de vista farmacodinâmico, pode-se categorizar as drogas de abuso de acordo com suas principais ações sobre os sistemas de neurotransmissão, embora devemos sempre ter em mente que, mesmo dentre as drogas de uma determinada categoria, existe grande heterogeneidade quanto a seus mecanismos de ação, os quais nem sempre são muito bem entendidos. Assim, seria possível traçar a seguinte classificação para as drogas de abuso:

- **Álcool:** presente em diferentes títulos em diferentes bebidas destiladas ou fermentadas, como o uísque, a cerveja, o rum, o saquê, o corote, a cachaça e o vinho.

- **Nicotina:** agonista total de receptores ionotrópicos de acetilcolina, primeiramente extraída da planta _Nicotiana tabacum_, pode ser encontrada em cigarros, charutos, essências para narguilês e nos _e-líquidos_ utilizados em _vapes_ (cigarros eletrônicos).

- **Derivados da maconha:** incluem o _skank_, uma espécie de "maconha sintética" e o haxixe, um exsudato resinoso extraído das glândulas presentes nos tricomas do terço superior de plantas femininas da espécie _Cannabis sativa_. Seus efeitos sobre o sistema de recompensa e outras áreas do córtex cerebral se dão pelas substâncias tetrahidrocanabidiol (THC), relacionado à euforia e às alucinações relatadas durante o uso, e canabidiol, amplamente pesquisado em razão de seus efeitos terapêuticos putativos para quadros de epilepsia, êmese induzida por medicamentos e doenças neurodegenerativas.

- **Hipnóticos e Sedativos:** destacam-se nesse grupo substâncias corriqueiramente utilizadas como fármacos, como o clonazepam (um benzodiazepínico), o zolpidem (um hipnótico muito potente) e o fenobarbital (barbitúrico utilizado para tratamento de epilepsias refratárias). Compartilham o mecanismo de ação comum de atuarem como moduladores alostéricos positivos de receptores $GABA_A$,assim como o álcool, sendo que quadros de intoxicação por essas substâncias podem levar ao óbito por parada respiratória na medida em que ocorre supressão importante de centros vegetativos bulbares, o que pode ser revertido com o uso do antídoto flumazenil.

- **Opioides:** essa classe farmacológica foi um marco na história da Anestesiologia e compreende uma série de alcaloides naturais extraídos da papoula ( _Papaver somniferum_ ), como a morfina, a codeína e a tebaína, e opioides sintéticos fabricados por meio da introdução ou da modificação de grupos funcionais dessas substâncias, a exemplo da heroína, da petidina, do fentanil, do tramadol e da metadona. Atuam em receptores opioides $\mu$, $\delta$ e $\kappa$ promovendo modulação da dor e inibição de interneurônios $GABA_B$ responsáveis por regularem a atividade da via mesolímbica, deixando-a hiperativa.

- **Estimulantes:** englobam substâncias como as anfetaminas, a cocaína, o metilfenidato, a atomoxetina e a efedrina, as quais atuam promovendo extravasamento de neurotransmissores excitatórios - especialmente a norepinefrina e a dopamina - de suas vesículas sinápticas, promovendo também o acúmulo destes no meio extracelular por meio de uma inversão na dinâmica de recaptação e transporte de proteínas de armazenamento vesicular como a $VMAT$ e de recaptação de neurotransmissores, como a $NET$, as quais passam a atuar como bombas de extrusão de neurotransmissores para o meio externo. Para o tratamento dos sintomas das crises de abstinência provocados pela retirada do uso dessas substâncias, podem ser empregados antipsicóticos e $\beta$-bloqueadores.

- **Alucinógenos:** abrigam um amplo rol de substâncias, muitas das quais são utilizadas como enteógenos por comunidades tradicionais e não possuem mecanismos de ação muito bem conhecidos. Nesse sentido, podemos citar como representantes dessa classe o ácido lisérgico (LSD), a psilocibina, a mescalina, o MDMA, o DMT (dimetiltriptamina) e os alcaloides $\beta$-carbolínicos encontrados na _ayahuasca_, na harmala e no cipó-mariri.

No que diz respeito às manifestações clínicas e aos sintomas das síndromes de abstinência relativas ao uso de cada uma das classes supramencionadas de drogas de abuso, pode-se dizer que estas são extremamente variadas e, em última instância, dependem não só de mecanismos de _up-regulation_ ou _down-regulation_ de receptores nas membranas neuronais como também de modificações ainda desconhecidas sobre os sistemas de neurotransmissão e neuromodulação. A mesma heterogeneidade pode ser verificada quanto às sensações relatadas mediante o uso dessas substâncias, uma vez que elas diferem significativamente entre si quanto a seus alvos de ação. Dessa forma, noticia-se:

- **Álcool:** constitui a droga de abuso mais consumida atualmente e atua como modulador alostérico positivo de receptores $GABA_A$, facilitando a ligação do ácido $\gamma$-aminobutírico a esse canal iônico operado por ligantes, proporcionando um influxo de íons $Cl^-$ que hiperpolariza a célula, fazendo com que seja mais difícil dela ser disparada. Nesse sentido, pequenas doses de álcool podem proporcionar euforia e comportamento social desinibido na medida em que neurônios de centros superiores responsáveis pela regulação do comportamento são inibidos. Entretanto, à medida que a alcoolemia aumenta (e, por apresentar uma cinética de eliminação de ordem zero, os níveis plasmáticos de etanol costumam variar erraticamente e serem de difícil controle em situações de intoxicação), essa inibição neuronal pode se disseminar para os núcleos da base, o cerebelo e o hipocampo, levando ao aparecimento de ataxia, descoordenação da marcha e amnésia anterógrada (a qual, a nível molecular, pode estar relacionada a subtipos de receptores neuronais que contêm uma subunidade $\alpha_5$).

- **Nicotina:** conforme postula Stephen Stahl, esse agonista total de receptores nicotínicos possui um potencial dependogênico estimado em 32% e atua no Sistema Nervoso Central ativando receptores nicotínicos e promovendo despolarização neuronal, que causa uma sensação de relaxamento e despertar. Em função de sua via de administração se dar pelo fumo (via inalatória), esses efeitos são observados de modo extremamente rápido. Acredita-se que sua atuação em receptores nicotínicos dos subtipos $(\alpha_7)_5$ e $(\alpha_4)_2(\beta_2)_3$ esteja envolvida nos aspectos psicológicos subjacentes a seu uso e à sua dependência.

- **Maconha e seus derivados:** ao atuarem em receptores canabinoides do tipo $CB_1$ distribuídos por grandes extensões do Sistema Nervoso Central de modo análogo a canabinoides endógenos derivados do ácido araquidônico, como a anandamida, o tetrahidrocanabinol (THC) e o canabidiol regulam a atividade de liberação de neurotransmissores por meio de terminais nervosos pré-sinápticos. Em baixas doses, isso parece se relacionar a sensações de relaxamento, tranquilidade e bem-estar, porém, se os níveis dessas substâncias se elevarem, o indivíduo poderá relatar crises psicóticas e alucinações. Vale ressaltar que as substâncias presentes na maconha podem provocar, mediante uso crônico, embotamento afetivo, dificuldades para dormir e em funções sociais, perda da personalidade e de habilidades, além de transtornos psicóticos. Isso é particularmente grave em adolescentes, uma vez que a organização citoarquitetural de suas vias de comunicação encefálicas ainda não se encontra completamente madura e a maconha parece promover proliferação sináptica desordenada, prejudicando o desenvolvimento neuropsicocognitivo.

- **Opioides:** além de atuar de modo similar às dinorfinas e endorfinas produzidas endogenamente durante situações estressantes a partir da clivagem da pré-opiomelanocortina e, por conseguinte, proporcionarem uma intensa analgesiaatuando em receptores na medula e na substância cinzenta periaquedutal, os opioides também parecem ativar a via mesolímbica dando uma sensação de "barato" ao se ligarem a receptores expressos em neurônios $GABA$érgicos moduladores dessa via e diminuir a ativação destes. Assim, ao fazer uso de um opioide potente como o fentanil, um indivíduo pode relatar uma sensação de prazer, relaxamento e bem-estar com cessação de suas dores, efeitos que podem ser seguidos de sonolência. No entanto, em quadros de intoxicação por opioides, os quais podem ser tratados com o uso do antagonista opioide naltrexona em sua forma inalável, é comum que o indivíduo apresente miose, xerostomia, cólicas e prurido. Vale ressaltar, no entanto, que para o tratamento da abstinência por retirada de opioide, recomenda-se utilizar a metadona, um opioide menos potente cuja meia-vida de eliminação longa impede a ocorrência de variações bruscas dos níveis das drogas em uso.

- **Sedativos e Hipnóticos:** como mencionado anteriormente, ao se utilizar um barbitúrico, um benzodiazepínico ou uma droga-Z e as moléculas desses fármacos ocuparem seus sítios alostéricos nos receptores $GABA_A$ (localizados nas regiões de transição entre as subunidades $\alpha$ e $\gamma$ desse canal iônico operado por ligantes), ocorre uma mudança conformacional nesse receptor que favorece a ligação das moléculas de $GABA$ (ácido $\gamma$-aminobutírico) a seus dois sítios ortostéricos situados na transição entre as subunidades $\alpha$ e $\beta$ dessas proteínas. Desse modo, nota-se uma inibição intensa da atividade neuronal, o que, embora seja benéfico para situações como o controle do estado de mal epiléptico (quadro para o qual se costuma administrar uma dose de ataque de 10 miligramas de diazepam intravenoso), pode levar à amnésia anterógrada, ataxia, marcha ebriosa, depressão respiratória e óbito, especialmente se esses medicamentos forem ingeridos junto com o álcool, que também atua potencializando a transmissão $GABA$érgica (vale lembrar que é exatamente esse o princípio da "boa noite Cinderela", droga de estupro que leva flunitrazolam em sua composição). Entretanto, em doses menores, essas drogas tendem a provocar sentimentos de tranquilidade intensa, relaxamento, sonolência e hipotonia muscular.

- **Estimulantes:** em vista de seus mecanismos de ação se centrarem na liberação neurotransmissores excitatórios para o meio extracelular, potencializando a ação destes sobre as sinapses, pode-se elencar como os principais efeitos agudos decorrentes do uso de drogas como a cocaína, a atomoxetina, o metilfenidato, a anfepramona (muito utilizado por caminhoneiros que realizam longas viagens noturnas) e a efedrina sensações de euforia e hipervigilância, acompanhadas de tendências maníaca, alerta extremo, palpitações, tremores, diaforese e midríase (percebe-se que alguns desses sintomas, especialmente aqueles que se manifestam a nível físico, encontram-se relacionados à hiperativação simpática). Essas substâncias possuem alto potencial de causarem dependência e a síndrome de abstinência por sua retirada é marcada por anedonia, desejo intenso de dormir intercalado por períodos de agitação e _craving_ pela droga, os quais podem ser tratados por meio de $\beta$-bloqueadores, fármacos que atuarão controlando os sintomas físicos supramencionados, e antipsicóticos. A tendência de indivíduos que fazem uso de estimulantes do SNC é de que, com o passar do tempo e com o desenvolvimento de tolerância às drogas menos potentes, eles busquem drogas capazes de promover a liberação de monoaminas de modo mais intenso.

- **Alucinógenos:** de um pondo de vista farmacodinâmico, os mecanismos de ação dessas drogas são variados, complexos e ainda incompreendidos, porém em grande parte estes parecem estar relacionados ao estado de humor do indivíduo que as consome, podendo seus efeitos serem fortemente influenciados por este. Dessa maneira, as alucinações visuais, auditivas, cenestésicas, olfativas e gustatórias apresentadas por pessoas que fazem uso de substâncias como o ácido lisérgico podem ser caracterizadas como _good trips_, nas quais o indivíduo se sente espiritualmente elevado e iluminado por forças divinas, ou _bad trips_, nas quais o usuário da droga - que provavelmente já se encontrava ansioso ou deprimido antes do consumo da substância - relata viver um verdadeiro pesadelo acordado, ouvindo vozes aterrorizantes e enxergando monstros. Ademais, um fenômeno pouco compreendido que pode ser causado por essas drogas são os _flashbacks_, períodos nos quais os indivíduos que já as utilizaram experienciam reviver seus momentos de contato com a substância. Em virtude de provocarem uma tolerância brusca e intensa, é raríssimo observar quadros de dependência para essa classe de drogas de abuso. 

De modo geral, os mecanismos fisiopatológicos subjacentes ao desenvolvimento de transtornos de dependência química e abuso de substâncias se relacionam à hiperativação da via mesolímbica cerebral (cuja hiperativação de seus neurônios dopaminérgicos também pode ser vista em transtornos psicóticos, explicando os sintomas positivos da esquizofrenia), uma espécie de sistema de recompensa endógeno é disparado toda vez que participamos de atividades prazerosas como forma de promover aprendizado de padrões de comportamento repetidos. Neuroanatomicamente, a via mesolímbica tem início nos núcleos da área tegmentar ventral do mesencéfalo, os quais se projetam para o núcleo _accumbens_, na base do telencéfalo, que projeta eferências para áreas terciárias situadas primordialmente no córtex pré-frontal, embora estas também possam se dirigir para a amígdala e para o hipocampo, o que é fundamental para se compreender a importância de fatores socioafetivos na patogênese da dependência química e a relevância das memórias relativas ao uso da substância para possíveis quadros de recaída. Inicialmente, o indivíduo dependente (que, muito mais do que uma simples predisposição genética, usualmente sofre de solidão, isolamento social e tristeza profunda), passa buscar a substância (não só a droga, como também comportamentos de risco, como jogos de azar) como forma de se livrar de suas angústias e a sensação de "barato" proporcionada pela ativação forçada da via mesolímbica funciona como reforço positivo para que esse sujeito recorra novamente à droga no futuro. Entretanto, a via mesolímbica se adapta rapidamente à neurotransmissão modificada em consequência do uso da droga, ocorrendo dessensibilização de seus neurônios por modificações covalentes de seus receptores $D_2$ ou ainda internalização destes em vesículas citoplasmáticas, de forma que passa a ser necessária uma dose muito maior da droga para se alcançar o mesmo efeito inicial, levando ao desenvolvimento da tolerância. Cabe ressaltar que as adaptações moleculares efetuadas pelos neurônios em resposta ao uso da droga podem fazer com que o indivíduo se sinta agitado, indisposto ou depressivo na ausência da substância, quando as condições de neurotransmissão forem restituídas a seus estados basais. Assim, o indivíduo passa a sofrer de um quadro de abstinência mediante a retirada da droga, o qual se caracteriza por desejo intenso de consumir a substância para se livrar dos sintomas físicos desconfortáveis causados por sua ausência, de forma que o reforço positivo representado pelo "barato" por esta provocado durante a fase inicial do processo de dependência é suplantada por um reforço negativo. Como curiosidade, vale mencionar que temos vias neurais específicas encarregadas por "frear" a atividade da via mesolímbica, muitas das quais se iniciam no córtex pré-frontal dorsolateral (DLPFC), região cuja densidade neuronal se encontra diminuída em indivíduos que sofrem de dependência química.

Vale salientar que os sintomas reportados na síndrome de abstinência por álcool (esse mesmo mecanimso também se aplicaria a outros moduladores alostéricos positivos de receptores $GABA_A$, como os benzodiazepínicos, os barbitúricos e as drogas-Z), como o famoso _delirium tremens_, podem ser explicados com base no fato de que, diante de uma situação de inibição prolongada causada por uma hiperpolarização decorrente da atividade aumentada de receptores $GABA_A$, os neurônios do Sistema Nervoso Central passam a internalizar tais receptores inibitórios em vesículas citoplasmáticas e expressar maiores quantidades de receptores glutamatérgicos $NMDA$ em seus terminais pós-sinápticos na tentativa de sofrerem maior excitação. No entanto, quando o álcool sai de cena e a neurotransmissão é reconstituída a seus estados pregressos, esses neurônios passam a ficar hiperexcitáveis, explicando, por exemplo, o tremor e a agitação da abstinência alcóolica.

Em se tratando do tratamento farmacológico dos transtornos de abuso de álcool e nicotina, condições que, de acordo com o $III$ Levantamento Nacional sobre o Uso de Drogas pela População Brasileira (FIOCRUZ), afetam, respectivamente, 2,3 e 4,8 milhões de pessoas em todo o território nacional, é possível destacar as seguintes estratégias farmacológicas:

**Para o tratamento do transtorno de dependência de álcool:**

- **Naltrexona:** esse análogo sintético da oximorfina atua como ANTAGONISTA de receptores opioides, eliminando o prazer relacionado ao consumo do álcool ao modular a atividade de neurônios da via mesolímbica por mecanismos ainda pouco conhecidos.

- **Acamprosato:** fármaco relativamente caro, pode ser utilizado para o tratamento do _craving_ pelo álcool bem como para o manejo de sintomas de abstinência, dado que atua como ANTAGONISTA de receptores glutamatérgicos do tipo $NMDA$.

- **Benzodiazepínicos:** podem ser administrados em pacientes que dão entrada em serviços de urgência apresentando tremores, ansiedade e agitação excessivos desencadeados por abstinência ao álcool, uma vez que atuarão como MODULADORES ALOSTÉRICOS POSITIVOS de receptores $GABA_A$, facilitando a neurotransmissão inibitória.

- **Dissulfiram:** comercializado com os nomes "Antabuse" e "Antietanol", esse fármaco atua como INIBIDOR IRREVERSÍVEL da enzima aldeído-desidrogenase, responsável por converter o acetaldeído, metabólito tóxico oriundo da biotransformação do etanol pela enzima álcool-desidrogenase, em acetato. Desse modo, toda vez que o paciente que faz uso de dissulfiram ingere álcool, ele passará a apresentar quadros de diarreia e vômito em decorrência do acúmulo de acetaldeído, o que constitui um reforço negativo para que ocorra interrupção do uso da substância. Ademais, por mecanismos até então não conhecidos (ou não revleados para o público geral), o dissulfiram também é capaz de provocar disgeusia toda vez que o paciente ingere álcool.

Cabe ressaltar que, para o tratamento de sintomas referentes à síndrome de abstinência alcóolica, o paciente também pode efetuar uso crônico de **antiepilépticos** como o topiramato, o valproato e a carbamazepina e de **antidepressivos tricíclicos** como a imipramina, que inibe os sistemas de recaptura de monoaminas, especialmente a norepinefrina, a serotonina e a dopamina, ou de **inibidores seletivos da recaptação de serotonina**, tais como a fluoxetina e a sertralina.

**Para o tratamento do transtorno de dependência de nicotina:**

- **Terapia de reposição de nicotina:** tem como objetivo auxiliar na cessação do hábito de fumar e auxiliar no manejo da abstinência nicotínica ao fornecer níveis plasmáticos de nicotina sustentados para a ativação de receptores nicotínicos espalhados pelo Sistema Nervoso Central, apresentando a vantagem de reduzir o consumo de substâncias carcinogênicas presentes no tabaco. A nicotina utilizada para esse propósito pode ser encontrada em inúmeras apresentações farmacêuticas, como chicletes, gomas, _sprays_ nasais, adesivos transdérmicos e pastilhas.

- **Bupropiona:** corresponde a um antidepressivo atípico que atua como INIBIDOR DA RECAPTAÇÃO DE NOREPINEFRINA E DOPAMINA e ANTAGONISTA de receptores nicotínicos. É um exemplo de pró-fármaco, uma vez que são seus metabólitos treo-hidrobupropiona e eritro-hidrobupropiona que exercem o efeito sobre os alvos farmacológicos. Acredita-se que possam atuar na via mesolímbica ao interferirem na transmissão dopaminérgica.

- **Vareniclina:** princípio ativo dos medicamentos "Champix" e "Chantix", a vareniclina age como AGONISTA total de receptores nicotínicos $(\alpha_7)_5$ e agonista parcial de receptores nicotínicos dos subtipos $(\alpha_4)_2(\beta_2)_3$, $(\alpha_4)_3(\beta_2)_2$ e $(\alpha_3)_m(\beta_4)_n$. Além disso, por mecanismos até então não explicados, é capaz de proporcionar o aparecimento de um gosto desagradável na boca, similar ao de esterco, quando o indivíduo faz uso do cigarro.

Cabe destacar que, apesar de apresentarem considerável eficiência, serem de grande valia no âmbito clínico e oferecerem estratégias invadoras para o tratamento de afecções multifatoriais de natureza extremamente complexa (a exemplo de uma vacina não-proteica para a nicotina, que atualmente se encontra na fase $III$ de seus estudos clínicos), as abordagens farmacológicas para o tratamento de transtornos de dependência devem vir sempre acompanhadas de medidas não-farmacológicas primordiais para o sucesso terapêutico, como a psicoterapia e a modificação dos hábitos de vida (deixar de frequentar cenas de uso da substância, por exemplo). Nesse sentido, convém destacar que organizações como os Alcóolicos e Narcóticos Anônimos (e, mais recentemente, os Jogadores Anônimos) podem se mostrar muito úteis para o acolhimento empático de pacientes que sofrem dos transtornos supramencionados, os quais em grande parte foram intensificados por uma rede de apoio inexistente ou fragilizada.

